### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by aral** [isomorphic-git/server#2]
## To reproduce

1. Clone this repository
2. `npm i`
3. `node .`

## What should happen

It should run.

## What actually happens

Error:

```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'isomorphic-git'
Require stack:
- /home/aral/small-tech/small-web/sandbox/server/middleware.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/aral/small-tech/small-web/sandbox/server/middleware.js:6:117)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/aral/small-tech/small-web/sandbox/server/middleware.js' ]
}
```

**Comment by aral** [comment]
If you `npm i isomorphic-git` and run `node .` again, it fails with:

```
/home/aral/small-tech/small-web/sandbox/server/middleware.js:10
plugins.set('emitter', ee)
        ^

TypeError: Cannot read property 'set' of undefined
    at Object.<anonymous> (/home/aral/small-tech/small-web/sandbox/server/middleware.js:10:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by aral** [comment]
Including `"isomorphic-git": "0.72.0"` in `package.json` removes the errors but I can’t get it to do anything. Tried `node . start demo`. Just exits.
